// ============================================================
// Kenney Space Station Kit — DEV constructor parts
// ============================================================

import type { PartDef } from "./builderPartTypes.ts";

const s = (name: string, label: string): PartDef => ({
  name,
  label,
  kit: "space",
});

export const SPACE_STATION_BUILDER_PARTS: Record<string, PartDef[]> = {
  spaceFloor: [
    s("floor", "Floor"),
    s("floor-corner", "Corner"),
    s("floor-detail", "Detail"),
    s("floor-panel", "Panel"),
    s("floor-panel-corner", "Panel corner"),
    s("floor-panel-end", "Panel end"),
    s("floor-panel-straight", "Panel straight"),
    s("balcony-floor", "Balcony floor"),
    s("balcony-floor-center", "Balcony center"),
    s("balcony-floor-corner", "Balcony corner"),
  ],
  spaceFrame: [
    s("structure", "Structure"),
    s("structure-panel", "Panel"),
    s("structure-barrier", "Barrier"),
    s("structure-barrier-high", "Barrier high"),
  ],
  spaceWalls: [
    s("wall", "Wall"),
    s("wall-detail", "Detail"),
    s("wall-banner", "Banner"),
    s("wall-corner", "Corner"),
    s("wall-corner-round", "Corner round"),
    s("wall-corner-banner", "Corner banner"),
    s("wall-corner-round-banner", "Round banner"),
    s("wall-pillar", "Pillar"),
    s("wall-pillar-banner", "Pillar banner"),
    s("wall-switch", "Switch"),
  ],
  spaceDoors: [
    s("door-single", "Door 1"),
    s("door-single-half", "Door ½"),
    s("door-single-closed", "Door closed"),
    s("door-double", "Door 2"),
    s("door-double-half", "Double ½"),
    s("door-double-closed", "Double closed"),
    s("wall-door", "Wall door"),
    s("wall-door-center", "Door center"),
    s("wall-door-edge", "Door edge"),
    s("wall-door-edge-banner", "Edge banner"),
    s("wall-door-banner", "Door banner"),
    s("wall-door-wide", "Wide door"),
    s("wall-door-wide-banner", "Wide banner"),
  ],
  spaceWindows: [
    s("wall-window", "Window"),
    s("wall-window-frame", "Frame"),
    s("wall-window-shutters", "Shutters"),
    s("wall-window-banner", "Window banner"),
  ],
  spaceStairs: [
    s("stairs", "Stairs"),
    s("stairs-ramp", "Ramp"),
    s("stairs-corner", "Corner"),
    s("stairs-corner-inner", "Inner corner"),
    s("stairs-handrail", "Handrail"),
    s("stairs-handrail-single", "Handrail 1"),
    s("stairs-small-center", "Small center"),
    s("stairs-small-corner", "Small corner"),
    s("stairs-small-corner-inner", "Small inner"),
    s("stairs-small-edge", "Small edge"),
    s("stairs-small-edge-handrail", "Edge rail"),
    s("stairs-small-edges", "Small edges"),
    s("stairs-small-edges-handrail", "Edges rail"),
  ],
  spaceFurniture: [
    s("bed-single", "Bed 1"),
    s("bed-single-cover", "Cover 1"),
    s("bed-double", "Bed 2"),
    s("bed-double-cover", "Cover 2"),
    s("chair", "Chair"),
    s("chair-armrest", "Armrest"),
    s("chair-armrest-headrest", "Headrest"),
    s("chair-cushion", "Cushion"),
    s("chair-cushion-headrest", "Cushion head"),
    s("chair-headrest", "Headrest"),
    s("table", "Table"),
    s("table-large", "Large table"),
    s("table-inset", "Inset"),
    s("table-inset-small", "Inset small"),
    s("table-display", "Display"),
    s("table-display-small", "Display sm."),
    s("table-display-planet", "Planet"),
  ],
  spaceTech: [
    s("computer", "PC"),
    s("computer-wide", "Wide PC"),
    s("computer-system", "System unit"),
    s("computer-screen", "Monitor"),
    s("display-wall", "Wall screen"),
    s("display-wall-wide", "Wide screen"),
  ],
  spaceContainers: [
    s("container", "Container"),
    s("container-flat", "Flat"),
    s("container-flat-open", "Flat open"),
    s("container-tall", "Tall"),
    s("container-wide", "Wide"),
    s("skip", "Skip"),
    s("skip-rocks", "Skip rocks"),
    s("rocks", "Rocks"),
  ],
  spacePipes: [
    s("pipe", "Pipe"),
    s("pipe-bend", "Bend"),
    s("pipe-bend-diagonal", "Bend diag."),
    s("pipe-end", "End cap"),
    s("pipe-end-colored", "Colored end"),
    s("pipe-ring", "Ring"),
    s("pipe-ring-colored", "Colored ring"),
  ],
  spaceRails: [
    s("rail", "Rail"),
    s("rail-narrow", "Narrow rail"),
    s("balcony-rail", "Balcony rail"),
    s("balcony-rail-center", "Balcony center"),
    s("balcony-rail-corner", "Balcony corner"),
  ],
};
