// ============================================================
// Kenney Space Station Kit — детали для DEV-конструктора
// ============================================================

import type { PartDef } from "./builderPartTypes.ts";

const s = (name: string, label: string): PartDef => ({
  name,
  label,
  kit: "space",
});

export const SPACE_STATION_BUILDER_PARTS: Record<string, PartDef[]> = {
  "Космос · пол": [
    s("floor", "Пол"),
    s("floor-corner", "Угол"),
    s("floor-detail", "Деталь"),
    s("floor-panel", "Панель"),
    s("floor-panel-corner", "Пан. угол"),
    s("floor-panel-end", "Пан. торец"),
    s("floor-panel-straight", "Пан. прям."),
    s("balcony-floor", "Балкон пол"),
    s("balcony-floor-center", "Балкон центр"),
    s("balcony-floor-corner", "Балкон угол"),
  ],
  "Космос · каркас": [
    s("structure", "Каркас"),
    s("structure-panel", "Панель"),
    s("structure-barrier", "Барьер"),
    s("structure-barrier-high", "Барьер выс."),
  ],
  "Космос · стены": [
    s("wall", "Стена"),
    s("wall-detail", "Деталь"),
    s("wall-banner", "Баннер"),
    s("wall-corner", "Угол"),
    s("wall-corner-round", "Угол скруг."),
    s("wall-corner-banner", "Угол баннер"),
    s("wall-corner-round-banner", "Скруг. баннер"),
    s("wall-pillar", "Пилон"),
    s("wall-pillar-banner", "Пилон баннер"),
    s("wall-switch", "Выключатель"),
  ],
  "Космос · двери": [
    s("door-single", "Дверь 1"),
    s("door-single-half", "Дверь ½"),
    s("door-single-closed", "Дверь закр."),
    s("door-double", "Дверь 2"),
    s("door-double-half", "Дв. ½"),
    s("door-double-closed", "Дв. закр."),
    s("wall-door", "Стена дверь"),
    s("wall-door-center", "Дверь центр"),
    s("wall-door-edge", "Дверь край"),
    s("wall-door-edge-banner", "Край баннер"),
    s("wall-door-banner", "Дверь баннер"),
    s("wall-door-wide", "Дверь шир."),
    s("wall-door-wide-banner", "Шир. баннер"),
  ],
  "Космос · окна": [
    s("wall-window", "Окно"),
    s("wall-window-frame", "Рама"),
    s("wall-window-shutters", "Жалюзи"),
    s("wall-window-banner", "Окно баннер"),
  ],
  "Космос · лестницы": [
    s("stairs", "Лестница"),
    s("stairs-ramp", "Пандус"),
    s("stairs-corner", "Угол"),
    s("stairs-corner-inner", "Угол внутр."),
    s("stairs-handrail", "Перила"),
    s("stairs-handrail-single", "Перила 1"),
    s("stairs-small-center", "Мал. центр"),
    s("stairs-small-corner", "Мал. угол"),
    s("stairs-small-corner-inner", "Мал. внутр."),
    s("stairs-small-edge", "Мал. край"),
    s("stairs-small-edge-handrail", "Край пер."),
    s("stairs-small-edges", "Мал. края"),
    s("stairs-small-edges-handrail", "Края пер."),
  ],
  "Космос · мебель": [
    s("bed-single", "Кровать 1"),
    s("bed-single-cover", "Покрывало 1"),
    s("bed-double", "Кровать 2"),
    s("bed-double-cover", "Покрывало 2"),
    s("chair", "Стул"),
    s("chair-armrest", "С подлок."),
    s("chair-armrest-headrest", "С подголов."),
    s("chair-cushion", "Подушка"),
    s("chair-cushion-headrest", "Подуш.+гол."),
    s("chair-headrest", "Подголовник"),
    s("table", "Стол"),
    s("table-large", "Стол бол."),
    s("table-inset", "Врезной"),
    s("table-inset-small", "Врезн. мал."),
    s("table-display", "Витрина"),
    s("table-display-small", "Витр. мал."),
    s("table-display-planet", "Планета"),
  ],
  "Космос · техника": [
    s("computer", "ПК"),
    s("computer-wide", "ПК шир."),
    s("computer-system", "Системник"),
    s("computer-screen", "Монитор"),
    s("display-wall", "Экран стена"),
    s("display-wall-wide", "Экран шир."),
  ],
  "Космос · контейнеры": [
    s("container", "Контейнер"),
    s("container-flat", "Плоский"),
    s("container-flat-open", "Плоск. откр."),
    s("container-tall", "Высокий"),
    s("container-wide", "Широкий"),
    s("skip", "Контейнер мусор"),
    s("skip-rocks", "Конт.+камни"),
    s("rocks", "Камни"),
  ],
  "Космос · трубы": [
    s("pipe", "Труба"),
    s("pipe-bend", "Изгиб"),
    s("pipe-bend-diagonal", "Изгиб диаг."),
    s("pipe-end", "Заглушка"),
    s("pipe-end-colored", "Загл. цвет"),
    s("pipe-ring", "Кольцо"),
    s("pipe-ring-colored", "Кольцо цвет"),
  ],
  "Космос · перила": [
    s("rail", "Перила"),
    s("rail-narrow", "Перила узк."),
    s("balcony-rail", "Балкон пер."),
    s("balcony-rail-center", "Балкон центр"),
    s("balcony-rail-corner", "Балкон угол"),
  ],
};
